[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "16.16.0"
  NPM_VERSION = "8.11.0"
  HUGO_VERSION = "0.109.0"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.next]
  command = "npm run build"

[context.next.environment]
  HUGO_ENV = "next"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
    baseUrl = "https://sq-web.netlify.app/"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = [
      "google",
      "yandex"
    ]

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

[[redirects]]
  from = "/install.sh"
  to = "https://raw.githubusercontent.com/neilotoole/sq/master/install.sh"
  status = 301


[[redirects]]
  from = "/a/*"
  to = "https://asciinema.org/a/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = '''
      default-src 'self' 'unsafe-inline' sq.io web.sq.io sq-web.netlify.app;
      script-src 'self' 'unsafe-inline' sq.io web.sq.io sq-web.netlify.app asciinema.org www.googletagmanager.com;
      frame-src 'self' sq.io web.sq.io sq-web.netlify.app asciinema.org;
      connect-src www.google-analytics.com;
      img-src 'self' sq.io web.sq.io sq-web.netlify.app www.netlify.com;
      style-src 'self' sq.io web.sq.io sq-web.netlify.app www.netlify.com fonts.googleapis.com;
      font-src 'self' sq.io web.sq.io sq-web.netlify.app fonts.googleapis.com cdnjs.cloudflare.com fonts.gstatic.com  fonts.googleapis.com github.com maxcdn.bootstrapcdn.com themes.googleusercontent.com use.fontawesome.com
      '''
