name: Publish on Netlify
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Publish
        uses: netlify/actions/build@master
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
